### ISSUE TITLE
setup.json and config status missing in git

### ISSUE THREAD

**Issue by hlostam** [marilenadaquino/crowdsourcing#36]
```
		reload(conf)
		f = forms.get_form('setup.json') <<<-this line
		data = u.get_vars_from_module('conf')
		return render.setup(f=f,user='anonymous',data=data)
```
The required `setup.json` file in `app.py` is missing (probably not commited).

The `config.py` file most likely misses the status which is expected in `app.py`:
```
class Login:
	def GET(self):
		if conf.status=='not modified':
```

**Comment by marilenadaquino** [comment]
commit [52a7a97c2f23f1e28cdc564de13291e561e453d1](https://github.com/marilenadaquino/crowdsourcing/commit/52a7a97c2f23f1e28cdc564de13291e561e453d1) and [14c89fb784707eda3201734da0a983b3466c2c52](https://github.com/marilenadaquino/crowdsourcing/commit/14c89fb784707eda3201734da0a983b3466c2c52)
